### ISSUE TITLE
Support todo system

### ISSUE THREAD

**Issue by stakiran** [stakiran/twdd#9]
# todo
- [x] how to remove done-todo? <- use hidemaru grep writing and tag jump
- [x] what is todo mark?
  - [X] ~~`@todo`~~ NG because its mean mention.
  - [X] ~~`todo`~~ NG because there is no difference between my todo and a word "todo" simply.

**Comment by stakiran** [comment]
# todolist
on windows, 

```bat
type tweets.md | findstr /c:@todo > todo.md
```

# see todo
fenrir incremental search: `twdd todo`

# remove todo
これめんどい。手作業で tweets.md から取り除くのはだるい。

**Comment by stakiran** [comment]
done. https://github.com/stakiran/twdd/tree/0125ee18de14be2e5c4bfc44a5a5d33bf0ada8c9
